# Generated by Django 3.0 on 2022-02-11 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ('full_name', 'topic'), 'verbose_name': 'Профессор', 'verbose_name_plural': 'Профессоры'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('account', 'age', 'group', 'gpa'), 'verbose_name': 'Студент', 'verbose_name_plural': 'Стундеты'},
        ),
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=20, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='full_name',
            field=models.CharField(max_length=20, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='topic',
            field=models.CharField(choices=[('java', 'Java'), ('python', 'Python'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('ruby', 'Ruby'), ('golang', 'GoLang'), ('sql', 'SQL'), ('swift', 'Swift'), ('php', 'PHP'), ('deplhi', 'Deplhi'), ('perl', 'Perl')], default='java', max_length=20, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='student',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Account'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.Group'),
        ),
    ]
