# Generated by Django 3.0 on 2022-02-16 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_auto_20220211_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ('full_name', 'topic'), 'verbose_name': 'Преподователь', 'verbose_name_plural': 'Преподователи'},
        ),
        migrations.AddField(
            model_name='account',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-15', verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время удаления'),
        ),
        migrations.AddField(
            model_name='account',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AddField(
            model_name='group',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-15', verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время удаления'),
        ),
        migrations.AddField(
            model_name='group',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AddField(
            model_name='professor',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-15', verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время удаления'),
        ),
        migrations.AddField(
            model_name='professor',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AddField(
            model_name='student',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-15', verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время удаления'),
        ),
        migrations.AddField(
            model_name='student',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='professor',
            name='topic',
            field=models.CharField(choices=[('java', 'Java'), ('python', 'Python'), ('typescript', 'TypeScrips'), ('ruby', 'Ruby'), ('golang', 'Golanfg'), ('sql', 'SQL'), ('swift', 'Swift'), ('php', 'PHP'), ('delphi', 'Delphi'), ('perl', 'Perl')], default='java', max_length=20, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(verbose_name='Средний бал'),
        ),
    ]
