# Generated by Django 3.0 on 2022-02-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateTimeCustom',
        ),
    ]
